# docker-compose.yml

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      #      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      #      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: gigs
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - app_network

  api:
    build:
      context: https://github.com/${GITHUB_USERNAME}/giggity-bun-api.git#main
    container_name: bun_api
    restart: always
    ports:
      - "8080:8080"
    environment:
      - MONGODB_URI=mongodb://localhost:27017
      - PORT=8080
    depends_on:
      - mongodb
    networks:
      - app_network

  frontend:
    build:
      context: https://github.com/${GITHUB_USERNAME}/giggityv2.git#main
    container_name: nextjs_frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - API_URL=http://api:8080
    depends_on:
      - api
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mongodb_data: